### ISSUE TITLE
Activate more python toolbox functions

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/transformers-extension#293]
We added the PTB in #201, but with reduced functionality. we need to:

* add release and publish with PTB
* for pylint: set fail-under higher(in pyproject.toml) and fix linter issues
* fix typing, reenable in pre-commit-config -> add following to pre-commit-config
 ```
  - repo: local
    hooks:
      - id: type-check
        name: type-check
        types: [ python ]
        pass_filenames: false
        language: system
        entry: poetry run nox -s lint:typing
        stages: [ pre-push ] 
```

* reenable code-format in pre-commit-config, then fix findings
```
  - repo: local
    hooks:
      - id: code-format
        name: code-format
        types: [ python ]
        pass_filenames: false
        language: system
        entry: poetry run nox -s project:fix
        stages: [ pre-commit ]
```
* once project passes code format checks, reenable in ci by adding the following to checks.yml
```
  Type-Check:
    name: Type Checking (Python-${{ matrix.python-version }})
    needs: [ Version-Check, build-matrix ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: 2.0.1

      - name: Run type-check
        run: poetry run nox -s lint:typing
```
* add this check to checks.yml again:
```
  Format:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
        with:
          python-version: "3.10"
          poetry-version: 2.0.1

      - name: Run format check
        run: poetry run nox -s project:format
```
* test Test task in checks.yml should deped ont he others, once done its should read:
```    
needs: [ Documentation, Lint, Type-Check, Security, Format, build-matrix ]
```
* potentially add class UpdateTemplates: to noxconfig.py? see toolbox docu
* for TE_integration_test_overwrite nox task: 
  * do we even want this override? since the integration tests should not run in github CI but aws instead?
  *  find out if this could also be done with just sending parameters to test:integration task.
  * decide if the task should include starting db and export slc?
   * check if   we can update itde to allow stopping with starting db seperateley?
* update documentaion regarding nox tasks
* reenable slow checks and trigger aws coudebuild from there?
