### ISSUE TITLE
enable PTB code format task in ci

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/transformers-extension#296]
We added the PTB in #201, but with reduced functionality. we need to:

- [x]  reenable code-format in pre-commit-config, then fix findings
```
  - repo: local
    hooks:
      - id: code-format
        name: code-format
        types: [ python ]
        pass_filenames: false
        language: system
        entry: poetry run nox -s project:fix
        stages: [ pre-commit ]
```
- [x]  once project passes code format checks, reenable in ci by adding the following to checks.yml

```
  Format:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
        with:
          python-version: "3.10"
          poetry-version: 2.0.1

      - name: Run format check
        run: poetry run nox -s project:format
```
- [x]  * Test task in checks.yml should depend on the others, once done its should read:
```    
needs: [ Documentation,  Security, Format, build-matrix ]
